- name: AWS S3 Github Action
  uses: keithweaver/aws-s3-github-action@v0.1.2
  with:
    command: cp
    source: ./local_file.txt
    destination: s3://yourbucket/folder/local_file.txt
    aws_access_key_id: ${{ secret.AWS_ACCESS_KEY_ID }}
    aws_secret_access_key: ${{ secret.AWS_SECRET_ACCESS_KEY }}
